AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - qa
      - prod
  DBPassword:
    Type: String
    NoEcho: true
  DBUser:
    Type: String
    Default: ebattle
  DBName:
    Type: String
    Default: ebattle_dev
  DBHost:
    Type: String
    Default: lamiadb1.ceoy3jbkraru.us-east-1.rds.amazonaws.com

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Handler: index.handler
    Layers:
      - !Ref DatabaseLayer
    Timeout: 3
    Tags:
      Project: Ebattle
      Team: Api
      Environment: !Ref Environment
    Environment:
      Variables:
        DB_PASSWORD: !Ref DBPassword
        DB_USER: !Ref DBUser
        DB_NAME: !Ref DBName
        DB_HOST: !Ref DBHost
        ENVIRONMENT: !Ref Environment
  HttpApi:
    Tags:
      Project: Ebattle
      Team: Api
      Environment: !Ref Environment

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Tags:
        - Key: Project
          Value: Ebattle
        - Key: Team
          Value: Api
        - Key: Environment
          Value: !Ref Environment
  LambdaRoleWithS3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Ebattle-S3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::ebattle-api-static-${Environment}
                  - !Sub arn:aws:s3:::ebattle-api-static-${Environment}/*
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Tags:
        - Key: Project
          Value: Ebattle
        - Key: Team
          Value: Api
        - Key: Environment
          Value: !Ref Environment
  AuthorizerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: InvokeAuthorizerFunction
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource: !GetAtt Authorizer.Arn
      Tags:
        - Key: Project
          Value: Ebattle
        - Key: Team
          Value: Api
        - Key: Environment
          Value: !Ref Environment

  DatabaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DatabaseLayer
      ContentUri: src/shared/database
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs18.x
      BuildArchitecture: arm64

  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/authorizer/
      Role: !GetAtt LambdaRole.Arn
  Log:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/_log/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /log
            Method: ANY
  AuthorizerLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/_log/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /log/auth
            Method: ANY
            Auth:
              Authorizer: Authorizer
  Api:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/documentation/
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /docs/api
            Method: GET
  Games:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/games/
      Role: !GetAtt LambdaRoleWithS3.Arn
      MemorySize: 512
      Events:
        EbattleApiGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games
            Method: get
            Auth:
              Authorizer: Authorizer
        EbattleApiCreate:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games
            Method: post
            Auth:
              Authorizer: Authorizer
        EbattleApiCommunity:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games/community
            Method: get
            Auth:
              Authorizer: Authorizer
        EbattleApiVisibility:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games/visibility
            Method: post
            Auth:
              Authorizer: Authorizer
        EbattleApiDuplicate:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games/duplicate
            Method: post
            Auth:
              Authorizer: Authorizer
        EbattleApiUpdate:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games
            Method: put
            Auth:
              Authorizer: Authorizer
        EbattleApiDelete:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /games
            Method: delete
            Auth:
              Authorizer: Authorizer
  Matches:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/matches/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApiGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /matches
            Method: get
            Auth:
              Authorizer: Authorizer
        EbattleApiGetResult:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /matches/result
            Method: get
            Auth:
              Authorizer: Authorizer
        EbattleApiPut:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /matches
            Method: post
            Auth:
              Authorizer: Authorizer
        EbattleApiPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /matches/start
            Method: post
            Auth:
              Authorizer: Authorizer
  Languages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/languages/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /languages
            Method: get
            Auth:
              Authorizer: Authorizer
  Login:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/login/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /login
            Method: post
  Register:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/register/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /register
            Method: post
  Users:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/users/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApiGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /users
            Method: get
            Auth:
              Authorizer: Authorizer
        EbattleApiPut:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /users
            Method: put
            Auth:
              Authorizer: Authorizer
  Categories:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/endpoints/categories/
      Role: !GetAtt LambdaRole.Arn
      Events:
        EbattleApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref EbattleApi
            Path: /categories
            Method: get
            Auth:
              Authorizer: Authorizer
  EbattleApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
      Auth:
        Authorizers:
          Authorizer:
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
            FunctionArn: !GetAtt Authorizer.Arn
            FunctionInvokeRole: !GetAtt AuthorizerFunctionRole.Arn
            Identity:
              Headers:
                - Authorization