name: Lint code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn install

      - name: Prettier
        run: yarn prettier --check "src/**/*.ts"

      - name: ESLint
        run: yarn eslint "{src,apps,libs}/**/*.ts"

      - name: Build
        run: yarn run build