name: 'Test pull request on AWS'

concurrency: staging_environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/setup-sam@v1

      - uses: actions/setup-node@v1
        with:
        node-version: 16.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build sam
        run: sam build

      - name: Deploy sam
        run: sam deploy --stack-name EbattleApiStaging --s3-bucket ebattle-api-staging --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset --on-failure DELETE --parameter-overrides DBName=ebattle_dev DBPassword=${{ secrets.DB_STAGING_PASSWORD }} Environment=staging

      - name: Npm install
        run: npm ci

      - name: Run tests
        run: NODE_ENV=staging npm run test

      - name: Delete sam
        if: always()
        run: sam delete --stack-name EbattleApiStaging --no-prompts
